Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,8 +38,8 @@ jobs:
           NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.${VERSION_PARTS[2]}"
           NEW_TAG="$VERSION_PREFIX$NEW_VERSION"
           echo "NEW_TAG: $NEW_TAG"
-          git tag $NEW_TAG
-          git push origin $NEW_TAG || echo "Failed to push tag"
+          git tag $NEW_TAG || (echo "Failed to create tag" && exit 1)
+          git push origin $NEW_TAG || (echo "Failed to push tag" && exit 1)
           echo ::set-output name=TAG_NAME::$NEW_TAG
       
       - name: Create Release
