Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,11 +14,9 @@ jobs:
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
-
       - name: Set up Git
         run: |
           git config --global user.name 'github-actions'
-
       - name: Create Tag
         id: create_tag
         env:
@@ -52,16 +50,4 @@ jobs:
           done
           echo "NEW_TAG: $NEW_TAG"
           git tag $NEW_TAG || (echo "Failed to create tag" && exit 1)
-          git push origin $NEW_TAG || (echo "Failed to push tag" && exit 1)
-          echo "::set-output name=TAG_NAME::$NEW_TAG"
-
-      - name: Create Release
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
-          release_name: Release ${{ steps.create_tag.outputs.TAG_NAME }}
-          draft: false
-          prerelease: false
+          git push origin $NEW_TAG || (echo "Failed to push tag" && exit 
